"""PR creation and management handler."""

from __future__ import annotations

import logging
from typing import Any

from src.integrations.atlassian.jira_client import JiraClient
from src.integrations.github.repo_client import GitHubRepoClient
from src.integrations.mcp_manager import MCPManager
from src.integrations.teams.notification_client import TeamsNotificationClient
from src.schemas.plan import Plan
from src.schemas.task import Task

logger = logging.getLogger(__name__)


class PRCreationHandler:
    """Creates pull requests with auto-generated descriptions and notifications."""

    def __init__(self, *, mcp_manager: MCPManager) -> None:
        self._mcp = mcp_manager

    async def create_pr(
        self,
        *,
        task: Task,
        plan: Plan,
        branch: str,
        github_client: GitHubRepoClient,
        jira_client: JiraClient,
        teams_client: TeamsNotificationClient,
    ) -> dict[str, Any]:
        """Create a PR, link to Jira, and notify Teams.

        Returns dict with pr_url and pr_number.
        """
        owner = "giftbee"
        repo = task.context.get("repository", "")

        # Generate PR content
        title = f"[{task.jira_key}] {task.title}"
        body = self.generate_pr_description(task, plan)

        # Create the PR
        pr = await github_client.create_pull_request(
            owner=owner,
            repo=repo,
            title=title,
            body=body,
            head=branch,
            base="main",
        )

        pr_url = pr.get("html_url", "")
        pr_number = pr.get("number", 0)

        logger.info("PRCreation: created PR #%d — %s", pr_number, pr_url)

        # Link PR to Jira ticket
        await jira_client.add_comment(
            issue_key=task.jira_key,
            body=f"PR created by Dev-AI: {pr_url}",
        )

        # Notify Teams
        await teams_client.send_message(
            channel_id="dev-ai-notifications",
            message=(
                f"**New PR for {task.jira_key}**\n"
                f"Title: {title}\n"
                f"Branch: `{branch}`\n"
                f"PR: {pr_url}\n"
                f"Subtasks completed: {task.completed_subtask_count}/{len(task.subtasks)}"
            ),
        )

        return {
            "pr_url": pr_url,
            "pr_number": pr_number,
            "title": title,
        }

    @staticmethod
    def generate_pr_description(task: Task, plan: Plan) -> str:
        """Generate a markdown PR body."""
        changed_files: list[str] = []
        for subtask in task.subtasks:
            changed_files.extend(subtask.file_paths)
        changed_files = sorted(set(changed_files))

        subtask_list = "\n".join(
            f"- [x] {step.description}" for step in plan.subtasks
        )

        file_list = "\n".join(f"- `{f}`" for f in changed_files) if changed_files else "- N/A"

        return f"""## Summary

Automated implementation for [{task.jira_key}] — {task.title}

{task.description}

## Changes

### Subtasks Completed
{subtask_list}

### Files Modified
{file_list}

## Test Plan
- [ ] All existing tests pass
- [ ] New tests added for changed functionality
- [ ] Manual verification of acceptance criteria

## Context
- **Jira:** {task.jira_key}
- **Complexity:** {plan.estimated_complexity}
- **Subtasks:** {len(plan.subtasks)}

---
*Generated by Dev-AI Agent System*
"""
